name: kdump-anaconda-addon tests

on: pull_request

jobs:
  lint-check:
    runs-on: ubuntu-latest
    container: docker.io/fedora:latest
    steps:
      - name: Install dependent packages for tests
        run: dnf install anaconda python-pytest python-blivet pylint make -yq

      - name: Check out repository 
        uses: actions/checkout@v4

      - name: lint check
        run: make runpylint

      - name: unit tests
        run: make unittest

